version: '3.4'
x-build: &build
  context: .
  dockerfile: Dockerfile

x-shared: &common
  image: base-build
  ipc: host
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEV_SOURCE=${DEV_SOURCE}
  volumes:
    - .:/src
    - ./notebooks:/notebooks
    - ${DATA_PATH:-./data}:/data
  env_file:
    - .env

services:
  notebook:
    <<: *common
    ports:
      - "8888:8888"